### ISSUE TITLE
Mod logs aren't appearing for r/CryptoCurrency

### ISSUE THREAD

**Issue by PhantomMod** [vitosamson/modlogs#18]
Title says it all. I made sure the bot has the wiki permission for the config page.

**Comment by PhantomMod** [comment]
For convenience: https://modlogs.fyi/r/CryptoCurrency

**Comment by vitosamson** [comment]
Hey, sorry about that. I'm looking into it right now. It looks like modlogs is running into issues with rate limiting on the reddit API, but I'm not sure if that's related to your sub.

**Comment by PhantomMod** [comment]
Okay, no problem. Thanks for letting me know what the problem was.

**Comment by vitosamson** [comment]
Hey @PhantomMod, I ended up bumping the memory in the server since prices came down and the initial import of r/CryptoCurrency logs was able to complete successfully. Looks good now.

Thanks for using modlogs, and for being patient while I sorted that out.
