### ISSUE TITLE
modlogs have disappeared on the site; u/modlogs does not accept invites

### ISSUE THREAD

**Issue by icecream42** [vitosamson/modlogs#21]
Refer to the title.

**Comment by icecream42** [comment]
Everything works again, not quite sure if this was a coincidence or not.

Nevertheless thanks for providing us with with this service!

**Comment by vitosamson** [comment]
There was an issue with one of the backend services. I restarted it this morning but didn’t get a chance to update this issue. Thanks for bringing it to my attention.
