### ISSUE TITLE
Muteuser actions do not show muted user

### ISSUE THREAD

**Issue by go1dfish** [vitosamson/modlogs#8]
https://modlogs.fyi/r/subredditcancer?actions=muteuser

https://www.reddit.com/r/subredditcancer/wiki/modlog_config

Maybe we need a show_mute_user option?

**Comment by vitosamson** [comment]
Thanks, I should be able to get to this some time after thanksgiving.

I've never muted a user before - is there a time period associated with it (like temporary bans) or is it essentially an on/off?

**Comment by vitosamson** [comment]
If you could share an entry from the raw reddit mod log for a mute and unmute event (with user and mod names redacted) that would be helpful.

**Comment by go1dfish** [comment]
I've never muted anyone either.  There is a 3 day time associated with it I don't think it's adjustable.

You can unmute a user as well.  I think the unmutes are created automatically after 3 days.

https://www.reddit.com/r/subredditcancer/about/log/.json?feed=c7b83b457469643f1912d5fee30e18dba808f351&user=publicmodlogs&limit=100&type=muteuser

https://www.reddit.com/r/subredditcancer/about/log/.json?feed=c7b83b457469643f1912d5fee30e18dba808f351&user=publicmodlogs&limit=100&type=unmuteuser
